version: '3'             # version of docker compose

services:                # your services
  mongodb-docker-app:                # container name for docker to use
    image: mongodb-docker-app:1.0    # the image name
    depends_on:
      - mongodb
    ports:                           # specify your port
      - 3000:3000 
  
  mongodb:               # container name for docker to use
    image: mongo         # the image name
    ports:               # specify your port
      - 27017:27017
    environment:           # enviromental variables
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      # mongodb-data is random name you can always change it.
      # the path is where mongodb stores its data in the container. for mysql the path will be /var/lib/mysql and postgres it will be /var/lib/postgres/data
      - mongodb-data:/data/db
    
  mongo-express:           # container name for docker to use
    image: mongo-express   # the image name
    ports:                 # specify your port
      - 8080:8081
    environment:            # enviromental variables
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

# define list of volumes your containers will be using
volumes:
  mongodb-data:
    driver: local  # create a local file system

  